### ISSUE TITLE
Can it be implemented in a project about Parchis/Parks?

### ISSUE THREAD

**Issue by ImanCol** [IdleHandsProject/pixopixel#11]
I am doing a project that uses Arduino and we came up with converting a Ludo game board called Parchis / Parques with ws2812b LEDs.

In total, it would take us almost 600 of these RGB LEDs.  And I'm scratching my head on how to turn each 1 through a Bluetooth module to an Apple where it will contain the intelligence of the programmed game.  The idea is that every time someone moves a tile, the board with the LEDs reflects the same movement.

I don't really know if Arduino can handle that much data so I was wondering if your project can handle this with ease.  Although I have not fully studied its operation and handle a large number of LEDs, I appreciate any help.

https://upload.wikimedia.org/wikipedia/commons/e/e1/Parcheesi.svg

**Comment by chunkysteveo** [comment]
The ESP is more than capable of turning on and off 600 addressable LEDs. But the Pixo only has 256 leds, not 600.

**Comment by ImanCol** [comment]
I have researched it and it seems ideal for the project.  Thanks.
